In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score,accuracy_score, confusion_matrix

Here we import all basic required lib


---

In [21]:
df = pd.read_csv("/content/hospital_readmissions_30k.csv")

Loading dataset

In [22]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
patient_id,1,2,3,4,5,6,7,8,9,10
age,74,46,89,84,32,75,47,18,68,23
gender,Other,Female,Other,Female,Other,Female,Male,Other,Male,Female
blood_pressure,130/72,120/92,135/78,123/80,135/84,139/100,139/79,153/81,111/76,142/72
cholesterol,240,292,153,153,205,194,168,210,218,186
bmi,31.5,36.3,30.3,31.5,18.4,33.5,27.1,26.3,30.4,21.3
diabetes,Yes,No,No,No,No,No,No,No,No,No
hypertension,No,No,Yes,Yes,Yes,Yes,Yes,No,Yes,No
medication_count,5,4,1,3,6,0,5,5,3,3
length_of_stay,1,3,1,10,4,10,8,2,8,3
discharge_destination,Nursing_Facility,Nursing_Facility,Home,Home,Nursing_Facility,Home,Home,Home,Home,Home
readmitted_30_days,Yes,No,No,No,No,No,No,No,No,No

Displaying first 10 rows of data

In [23]:
df.shape

(30000, 12)

Checking shape of dataset

In [24]:
df.columns

Index(['patient_id', 'age', 'gender', 'blood_pressure', 'cholesterol', 'bmi',
       'diabetes', 'hypertension', 'medication_count', 'length_of_stay',
       'discharge_destination', 'readmitted_30_days'],
      dtype='object')

In [25]:
df.dtypes

patient_id                 int64
age                        int64
gender                    object
blood_pressure            object
cholesterol                int64
bmi                      float64
diabetes                  object
hypertension              object
medication_count           int64
length_of_stay             int64
discharge_destination     object
readmitted_30_days        object
dtype: object

Checking data type of every variableṁ in dataset

In [26]:
df.isnull().sum()
print(df.isnull().sum())

patient_id               0
age                      0
gender                   0
blood_pressure           0
cholesterol              0
bmi                      0
diabetes                 0
hypertension             0
medication_count         0
length_of_stay           0
discharge_destination    0
readmitted_30_days       0
dtype: int64

Checking for null or missing values

In [27]:
X = df.drop("readmitted_30_days", axis=1)
Y = df["readmitted_30_days"]
print(X.head())
print(Y.head())

   patient_id  age  gender blood_pressure  cholesterol   bmi diabetes  \
0           1   74   Other         130/72          240  31.5      Yes
1           2   46  Female         120/92          292  36.3       No
2           3   89   Other         135/78          153  30.3       No
3           4   84  Female         123/80          153  31.5       No
4           5   32   Other         135/84          205  18.4       No

  hypertension  medication_count  length_of_stay discharge_destination
0           No                 5               1      Nursing_Facility
1           No                 4               3      Nursing_Facility
2          Yes                 1               1                  Home
3          Yes                 3              10                  Home
4          Yes                 6               4      Nursing_Facility
0    Yes
1     No
2     No
3     No
4     No
Name: readmitted_30_days, dtype: object

Separating the input and output with a target column

In [28]:
X = pd.get_dummies(X, drop_first=True)
print(X.head())

   patient_id  age  cholesterol   bmi  medication_count  length_of_stay  \
0           1   74          240  31.5                 5               1
1           2   46          292  36.3                 4               3
2           3   89          153  30.3                 1               1
3           4   84          153  31.5                 3              10
4           5   32          205  18.4                 6               4

   gender_Male  gender_Other  blood_pressure_110/70  blood_pressure_110/71  \
0        False          True                  False                  False
1        False         False                  False                  False
2        False          True                  False                  False
3        False         False                  False                  False
4        False          True                  False                  False

   ...  blood_pressure_160/94  blood_pressure_160/95  blood_pressure_160/96  \
0  ...                  False                  False                  False
1  ...                  False                  False                  False
2  ...                  False                  False                  False
3  ...                  False                  False                  False
4  ...                  False                  False                  False

   blood_pressure_160/97  blood_pressure_160/98  blood_pressure_160/99  \
0                  False                  False                  False
1                  False                  False                  False
2                  False                  False                  False
3                  False                  False                  False
4                  False                  False                  False

   diabetes_Yes  hypertension_Yes  discharge_destination_Nursing_Facility  \
0          True             False                                    True
1         False             False                                    True
2         False              True                                   False
3         False              True                                   False
4         False              True                                    True

   discharge_destination_Rehab
0                        False
1                        False
2                        False
3                        False
4                        False

[5 rows x 1592 columns]

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [30]:
model = LogisticRegression(penalty="l2", max_iter=5000)

In [14]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=5000)

In [15]:
Y_prob = model.predict_proba(X_test)[:, 1]

In [16]:
Y_pred = model.predict(X_test)

In [17]:
auc = roc_auc_score(Y_test, Y_prob)
print("AUC:", auc)

AUC: 0.5803550853059396

accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

In [18]:
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8718333333333333

In [19]:
print("\nConfussion Matrix:")
print(confusion_matrix(Y_test, Y_pred))

Confussion Matrix:
[[5231    0]
 [ 769    0]]